### ISSUE TITLE
Design Suggestion

### ISSUE THREAD

**Issue by maurojuniorr** [kmikiy/SpotMenu#10]
Dude i like and  use your application, I'm here proposing a design that I think would look nice

![proposta de design](https://cloud.githubusercontent.com/assets/25700342/22851407/2005beb0-eff7-11e6-9b22-60b5b950cabe.png)

- Taking advantage of the current design, I did a little editing in photoshop and I will explain the design.

- The art of the album covers the whole tab

- The forward and rewind controls would be paired with the current play / pause that appears when we move the mouse.

- The artist information, music and tempo of the song could stay the same way and in the same place.

I hope you like the suggestions

**Comment by kmikiy** [comment]
cool, I'll get into. Although I think I'll have to add some sort of white blur behind the control buttons and labels so they can still look nice on darker artwork images.

**Comment by maurojuniorr** [comment]
I made two prototypes using a blur on the cover, shadow and outline on the controls and tempo of the song, the color is a light gray tone. This way I got a good result in light and dark covers. I do not know if you agree but I removed the information of name of the song and author, it was a bit redundant since it appears in the menu bar.

![proposta de design 3 fundo branco](https://cloud.githubusercontent.com/assets/25700342/22855220/b3ddd8a6-f052-11e6-8e8d-3788266e7bd8.png)


![proposta de design 3 fundo escuro](https://cloud.githubusercontent.com/assets/25700342/22855222/bb6b9202-f052-11e6-92c7-0e386c52a773.png)

The principle would be the same only blurs and the controls appear when we move the mouse.


I also did two samples of what it would look like with the music information

![proposta de design 2 blur e sombra](https://cloud.githubusercontent.com/assets/25700342/22855258/aa42cbca-f053-11e6-8445-b797e55b6fe1.png)

![proposta de design 3 fundo branco com nome](https://cloud.githubusercontent.com/assets/25700342/22855263/b5c850a0-f053-11e6-850a-80c413095e0b.png)

**Comment by kmikiy** [comment]
I have updated the layout based on your suggestions.
Normal view:
![screen shot 2017-02-21 at am 8 50 24](https://cloud.githubusercontent.com/assets/14206503/23155450/ee2a9310-f812-11e6-8c6d-8b4cc3836bf8.png)
Hover view:
![screen shot 2017-02-21 at am 8 50 14](https://cloud.githubusercontent.com/assets/14206503/23155455/f0e0da9c-f812-11e6-9f36-c2e31d44d7db.png)
