### ISSUE TITLE
Show Album Artist instead of Track Artist

### ISSUE THREAD

**Issue by camdenb** [kmikiy/SpotMenu#11]
Looks like the artist information is getting pulled in from the first artist on a track, when I think that pulling the info in from the album artist would make more sense for most use-cases.

In these screenshots, the album is "The College Dropout" by Kanye West, but since the track "Slow Jamz" has Twista listed as the first artist, SpotMenu displays his name as the artist.
<img width="360" alt="screen shot 2017-02-21 at 9 41 28 am" src="https://cloud.githubusercontent.com/assets/6440850/23177199/d064675e-f81a-11e6-8ca7-e9824bfd5e2b.png">
<img width="277" alt="screen shot 2017-02-21 at 9 46 59 am" src="https://cloud.githubusercontent.com/assets/6440850/23177198/d05e896a-f81a-11e6-9af8-63917d078ce4.png">

**Comment by kmikiy** [comment]
Good idea, I'll fix this

**Comment by kmikiy** [comment]
Fixed it. Please test it. Slow Jamz is the only song unavailable from that album in my country... 😓

**Comment by camdenb** [comment]
Wow, that's unfortunate (and a strange coincidence)! I'll test when I get home from work (in around 4-5 hours).
