### ISSUE TITLE
Sometimes not working properly

### ISSUE THREAD

**Issue by agnguyen** [kmikiy/SpotMenu#111]
### Description

I'll open Spotmenu while playing Spotify and the song will appear in the menubar (like normal), but then I'll go to a different application (like google chrome) and the artist will just disappear from the menubar (just gone from the menubar altogether, no Spotmenu logo or anything), but then I'll skip a song or 2 and it'll just reappear in the menubar, but a few songs later it might go away again. For the songs where it wasn't showing, all I had to do was click Spotify or Spotmenu, but then when going back to something else (like google chrome) it just went away again and the same process as above would just repeat. 

### Steps to Reproduce

1. open Spotify and play a playlist
2. open Spotmenu
3. open another application

**Expected behavior:** [What you expect to happen]
For the song and artist to always be shown in the menubar when using other applications

**Actual behavior:** [What actually happens]
The song and artist disappear when switching applications

**Reproduces how often:** [What percentage of the time does it reproduce?]
75%

### Versions

SpotMenu version: [Version of SpotMenu]
1.8

MacOS version: [Version of MacOS]
10.13.2

-Thank you

**Comment by Zazerr** [comment]
https://github.com/kmikiy/SpotMenu/issues/71

**Comment by agnguyen** [comment]
Thank you
I wanted to make sure that this wasn't a duplicate, but I guess I somehow didn't notice all the posts with the same question. Sorry
