### ISSUE TITLE
App disappears when a specific song is playing.

### ISSUE THREAD

**Issue by drguybh** [kmikiy/SpotMenu#113]
### Description
The app completely disappears from the menu bar every time a specific song is playing in Spotify. When the song is paused, the SpotMenu icon appears as expected. But when the song is played again, all signs of the app in the menu bar disappear. I’m reporting this in case it’s part of a broader issue, e.g., something to do with the French accented characters in the track name?

### Steps to Reproduce

1. Play this song in Spotify:
https://open.spotify.com/track/27cvNIRYgNqDGki4r49lxF?si=7lOvm7xUTXClGpL8q022lQ

2. My preferences are as follows:
![screen shot 2018-02-02 at 14 26 37](https://user-images.githubusercontent.com/36077513/35737923-21ce44f0-0825-11e8-8665-b613a353fc90.png)

### Versions

SpotMenu version: 1.8.0

You can get this information by highlighting SpotMenu.app (most likely in your Applications folder) in finder and pressing space.

MacOS version: 10.13.3

**Comment by kmikiy** [comment]
Hey 👋🏻
Thanks for reporting the issue. This is most likely the same problem that is addressed in these issues:
#77, #71, #16

**Comment by drguybh** [comment]
Thanks!
