### ISSUE TITLE
SpotMenu from https://kmikiy.github.io/SpotMenu/ installs malware apps

### ISSUE THREAD

**Issue by filipinascimento** [kmikiy/SpotMenu#120]
### Description

Hi, nice App. I tried to install it from the official website but it seems that the download link was hijacked and now the directs to:

http://partners5.admedit.net/affiliates/?adown=7251&cmp=54251&ctrack=[CLICK_ID]&ptrack=[SUB_ID]

which installs malware applications such as Advanced Mac Cleaner and tries to change the homepage/search engine of browsers.

### Steps to Reproduce

1. Go to https://kmikiy.github.io/SpotMenu/
2. Click download
3. install the software
4. now you have advanced mac cleaner, some homepage and search engine changed to incredible services such as anysearch. 

**Expected behavior:** 

Have spotmenu installed and working as in the github zip file.

**Actual behavior:**
Installs a bunch of malware.

**Reproduces how often:**
Everytime

### Versions

SpotMenu version: Current
MacOS version: High Sierra

**Comment by kmikiy** [comment]
Thanks for informing me. Hopefully, everything should be back to normal
