### ISSUE TITLE
Feature Request: Align Spotmenu icon to right of track details

### ISSUE THREAD

**Issue by cheqpat** [kmikiy/SpotMenu#128]
E.g. instead of showing the following:
<img width="514" alt="screen shot 2018-06-26 at 2 56 39 am" src="https://user-images.githubusercontent.com/20546986/41897454-00c34736-78ed-11e8-929d-5211f3e69e43.png">

The option to show the following could be given.
<img width="514" alt="2" src="https://user-images.githubusercontent.com/20546986/41897453-00a99552-78ed-11e8-9db5-f4d05de92d53.png">

**Comment by roflmaooooo** [comment]
+1 on this, it looks more elegant when all icons grouped up to the right of the text
