### ISSUE TITLE
Something happens with the art of the album

### ISSUE THREAD

**Issue by maurojuniorr** [kmikiy/SpotMenu#13]
Then friend, I'm here again!
Well I realized the art of the album gets high brightness when using MacOS dark mode, and a bit low when we use the normal mode. My version of MacOS is: Sierra 10.12.3

![captura de tela 2017-02-21 as 17 52 54](https://cloud.githubusercontent.com/assets/25700342/23187158/36ed44a6-f860-11e6-90a5-16f0c87681cb.png)

![captura de tela 2017-02-21 as 17 54 34](https://cloud.githubusercontent.com/assets/25700342/23187160/39869ec4-f860-11e6-9ae3-da5d43a15a1f.png)

And this is the image of spotify
![captura de tela 2017-02-21 as 18 05 48](https://cloud.githubusercontent.com/assets/25700342/23187234/7c957370-f860-11e6-95ac-1f3ec12c4806.png)

Another example...

![captura de tela 2017-02-21 as 17 58 12](https://cloud.githubusercontent.com/assets/25700342/23187265/9192c5a2-f860-11e6-966e-f02fb324ea4f.png)

![captura de tela 2017-02-21 as 17 58 31](https://cloud.githubusercontent.com/assets/25700342/23187274/96e9ad36-f860-11e6-8c39-73ce85e51313.png)

Album art from spotify

![captura de tela 2017-02-21 as 18 07 41](https://cloud.githubusercontent.com/assets/25700342/23187303/abe84f8a-f860-11e6-9062-ede9deea9b76.png)

**Comment by kmikiy** [comment]
Thanks for noticing. Fixed it.
![screen shot 2017-02-22 at am 8 05 26](https://cloud.githubusercontent.com/assets/14206503/23200664/dc86d8bc-f8d5-11e6-8343-4261ca170810.png)
![screen shot 2017-02-22 at am 8 05 03](https://cloud.githubusercontent.com/assets/14206503/23200704/1b5620de-f8d6-11e6-9ac3-774bc705c86f.png)
