### ISSUE TITLE
Album art is dimmed on Mojave OS in Light Mode

### ISSUE THREAD

**Issue by ronier83** [kmikiy/SpotMenu#156]
### Description

after installing the spotify and the SpotMenu
i am playing songs and the album art is dimmed (greyed out).
also it is dimmed in the widget 

![image](https://user-images.githubusercontent.com/45940350/50088074-ab659300-020a-11e9-8040-4055476f22e5.png)

![image](https://user-images.githubusercontent.com/45940350/50088043-95f06900-020a-11e9-8489-4936f1bbce64.png)

1. play song on spotify
2. open the spotmenu
3. album art is dimmed

album art should not be dimmed

album art is dimmed

happens 100% of times

SpotMenu version: 1.8.0

MacOS version: Mojave OS 10.14.2

You can get this information by clicking the  logo on the top left of your menu bar and selecting About This Mac.

**Comment by kmikiy** [comment]
Hey 👋🏻
This has been fixed. You can test it in the latest beta build [here](https://github.com/kmikiy/SpotMenu/releases/download/v1.8/beta.zip).

**Comment by ronier83** [comment]
awesome works great!
![image](https://user-images.githubusercontent.com/45940350/50088915-fed8e080-020c-11e9-86ad-7836a0ee8e72.png)
