### ISSUE TITLE
The song title float up

### ISSUE THREAD

**Issue by chaucerling** [kmikiy/SpotMenu#164]
Whatever only  English letter or Chinese/Japanese character, the song title maintains float up.

SpotMenu version: 1.90

MacOS version: 10.11.6

![image](https://user-images.githubusercontent.com/6396793/50727091-b4ce8500-1150-11e9-8b65-93f8e518615f.png)

**Comment by lxyyc** [comment]
I have the same issue and now it's solved.
Try quit the spotmenu from your menu bar and open it again, this would help.

**Comment by chaucerling** [comment]
It works, thank you
