### ISSUE TITLE
Doesn't available in Homebrew

### ISSUE THREAD

**Issue by herau** [kmikiy/SpotMenu#17]
Could be nice to have this software in homebrew 👍 

https://brew.sh/

**Comment by camden** [comment]
@herau SpotMenu is available via Homebrew Cask (https://caskroom.github.io/)

**Comment by herau** [comment]
@camden thanks a lot !

**Comment by kmikiy** [comment]
Hey @camden how does this homebrew cask work? I mean I know how to install stuff using it, but how does it know where to download the latest version of SpotMenu from?

**Comment by SyberToto** [comment]
@kmikiy I just find your app and I like it. I happen to install it with brew cask, and it isn't the latest version. So I dig into brew cask a little bit. It seems the version is controlled in [this file](https://github.com/caskroom/homebrew-cask/blob/master/Casks/spotmenu.rb), but I'm not sure. If it is how brew cask works, you may need to update this file once you get a new release.

**Comment by lucasbento** [comment]
Indeed it doesn't have the latest version.

Also, installation through it should be added to README since it's the easiest way to install the app.

**Comment by kmikiy** [comment]
@lucasbento I've updated it to download `1.6` following these [instructions](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask). I'm guessing it will be available once the [Pull Request](https://github.com/caskroom/homebrew-cask/pull/38935) is accepted. 
Update: it has been accepted

**Comment by lucasbento** [comment]
@kmikiy: just installed with it, works good, thanks!

**Comment by kmikiy** [comment]
Perfect 🙌🏻
Also I updated the README.
Thank you for your contribution.
