### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by RotJoch** [kmikiy/SpotMenu#189]
### Description

[so ive downloaded the spotmenu but when i open the folder i cant find spotmenu.app to download or drop in my files

#

**Expected behavior:** that i can use it

**Actual behavior:** [i cant use it

**Reproduces how often:** always

### Versions

SpotMenu version: [1.9
You can get this information by highlighting SpotMenu.app (most likely in your Applications folder) in finder and pressing space.

MacOS version: macOS mojave

You can get this information by clicking the  logo on the top left of your menu bar and selecting About This Mac.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by kmikiy** [comment]
hi, you probably downloaded the source code instead of the binary.
Heres the binary: https://github.com/kmikiy/SpotMenu/releases/download/v1.9/SpotMenu190.zip

Here are some steps to start the app if you get an error: https://support.apple.com/kb/PH25088?locale=en_US
