### ISSUE TITLE
Issue with v 1.4.1 on Mac

### ISSUE THREAD

**Issue by rsumana** [kmikiy/SpotMenu#21]
OS - Sierra (10.12.4)
Version 1.4.1 is glitchy. The icon in the menu bar seems to be blinking and the song name/info is not displayed in the menu bar. I downloaded Version 1.4 and ran it and it works fine.

**Comment by kmikiy** [comment]
Just (hopefully) fixed everything. You can download it here [updated version](https://github.com/kmikiy/SpotMenu/releases/download/v1.4.1/SpotMenu.zip) or download the source code and build it.
Note that the default behaviour  now is to hide artist/title and playing information. To change that, right click on the SpotMenu icon -> preferences. The changes will be persisted.
Let me know if you find anything. Feel free to reopen this issue.

**Comment by rsumana** [comment]
Works perfectly! Love this app - Great job guys! :)
