### ISSUE TITLE
SpotMenu no longer works with Apple Music.

### ISSUE THREAD

**Issue by akshaysalunke13** [kmikiy/SpotMenu#219]
### Description

SpotMenu doesn't recognize music playing in Apple Music

### Steps to Reproduce

1. Open Spot menu
2. Play music in Apple music

**Expected behavior:** SpotMenu detects music and shows current song info

**Actual behavior:** Nothing shows up in the menu bar

**Reproduces how often:** Always

### Versions

SpotMenu version: 1.9.0

MacOS version: 10.15.2

**Comment by kmikiy** [comment]
https://github.com/kmikiy/SpotMenu/issues/196 you can find a build where this is fixed here

**Comment by akshaysalunke13** [comment]
Sorry but I assumed the latest version 1.9.0 would include that patch by default?

**Comment by kmikiy** [comment]
version 1.9 was released before catalina went public
