### ISSUE TITLE
Focus ring shows on open

### ISSUE THREAD

**Issue by TrevorSayre** [kmikiy/SpotMenu#22]
![image](https://cloud.githubusercontent.com/assets/421548/25726642/2d5fd3ec-30f3-11e7-8122-f54241c2e03e.png)

This looks a little awkward. It shows when I click on the title in the menu bar, the standard action. It is a focus ring for cycling through the buttons with the tab key. It should probably have nothing selected at first, and first press of tab could cycle the focus ring on to the first button. Or at the very least have the focus ring start on the more commonly used button: pause/play or next. Previous track is definitely not the most used button.

**Comment by drpiou** [comment]
I have a similar issue. The left button get focused every time I click any action (next, pause, play, ...).

**Comment by kmikiy** [comment]
hmm, i'll figure out what's going on and try to fix it. By the way, do you guys have any special system settings turned on like accessibility settings? I'm asking, cause I can't recreate the bug

**Comment by drpiou** [comment]
@kmikiy The only thing, I guess, that could maybe make the difference is that I activated "All controls" in Keyboard > Shortcuts > "Full Keyboard Access: ...". If you have any other preferences you want to know from me, don't hesitate to ask.

**Comment by TrevorSayre** [comment]
@kmikiy I also have `Full Keyboard Access` enabled for `All controls`.

![image](https://cloud.githubusercontent.com/assets/421548/25865023/81702732-34bf-11e7-8430-a87195c62b76.png)

**Comment by kmikiy** [comment]
Thanks guys, I managed to fix it (partially). Focus ring isn't visible now (but is still navigated through when pressing tab, just doesn't show the ugly ring). I don't know how to disable it completely. You can pull the latest version and build it or download the [binary](https://github.com/kmikiy/SpotMenu/files/987823/SpotMenu.zip).

**Comment by kmikiy** [comment]
Feel free to reopen issue if you find anything related
