### ISSUE TITLE
Opening preferences when menu bar icon disabled

### ISSUE THREAD

**Issue by KhushrajRathod** [kmikiy/SpotMenu#236]
Hi, I just installed SpotMenu and was experimenting with preferences. I remember unchecking everything, and then I quit SpotMenu to get the changes to apply. Now I can't open preferences again, as there's no Menu bar icon, I don't see the Menu Bar change to "SpotMenu".  I've tried brew cask zapping, but there's no zap stanza. I've even tried removing the preferences plist, yet I don't see any sign of SpotMenu opening

SpotMenu version: v1.9
MacOS version: 10.15.5 (19F101)

**Comment by kmikiy** [comment]
open up the terminal.app and run this command `defaults delete com.kmikiy.SpotMenu` this should reset everything to the default settings. If you're running a newer version you might have to run this as well: `defaults delete hu.kmikiy.SpotMenu`

**Comment by KhushrajRathod** [comment]
Neither of them exist :/

![Screenshot 2020-07-06 at 11 56 45 AM](https://user-images.githubusercontent.com/44947946/86562138-afbee180-bf51-11ea-9a6e-28eb7bb53f9f.png)

**Comment by KhushrajRathod** [comment]
Ah wait... I think I got the issue. The menubar icon _did_ exist, only it was invisible - I didn't realize it was there.
Thanks for your help. You may want to create a shortcut or some other way to open preferences
