### ISSUE TITLE
Add Open at Login toggle to preferences

### ISSUE THREAD

**Issue by kevinlawler** [kmikiy/SpotMenu#25]
Add an `Open at Login` or `Start SpotMenu at Login` toggleable item

**Comment by benmillett** [comment]
Seconded!

**Comment by kmikiy** [comment]
Added open at login to preferences in version 1.4.2. Latest version can be downloaded [here](https://github.com/kmikiy/SpotMenu/releases/download/v1.4.2/SpotMenu.zip) or you can download the source code and build it yourself! Thanks for the feedback. 

Feel free to reopen this issue if somethings not working properly

**Comment by kevinlawler** [comment]
Thanks much, using the new version.
