### ISSUE TITLE
Delay in case of status/song changes

### ISSUE THREAD

**Issue by Desentyer** [kmikiy/SpotMenu#26]
If I press the pause button on my MacBook keyboard, the playing icon doesn't change instantly and it takes some seconds. There is some kind of delay. Maybe its possible to reduce the delay or adjust the app to have no delay. 
It's the same with the song title: If you press next, it takes a few seconds to change the title/artist in the bar.

**Comment by kmikiy** [comment]
AppDelegate.swift line:60
```swift
 timer = Timer.scheduledTimer(timeInterval: 0.3, target: self, selector: #selector(AppDelegate.postUpdateNotification), userInfo: nil, repeats: true)
```

I changed timeInterval from 5 to 0.3.
You can download the binary here:
[SpotMenu.zip](https://github.com/kmikiy/SpotMenu/files/1018440/SpotMenu.zip)

Later, I will add on option in the preferences pane to set this manually. Personally, the maximum 5 second delay didn't bother me. But everyone has different preferences 🙂

**Comment by Desentyer** [comment]
Wow very fast "resolve" :D awesome!
