### ISSUE TITLE
Xcode closing issue

### ISSUE THREAD

**Issue by jazzerjazzer** [kmikiy/SpotMenu#28]
Hey, thanks for the great app! 
I have a question rather than an issue: SpotMenu is also closed after I close the Xcode after running it. Is it an expected behaviour?  How can I prevent SpotMenu to be closed even though I close Xcode?
Thanks!

**Comment by kmikiy** [comment]
Hi,
If you pressed the play button in Xcode to start the app then that's normal.
If you don't want the app to close after Xcode has been closed, copy the .app file to your Applications folder, then you can launch it from the Launchpad.
<img width="508" alt="screen shot 2017-07-03 at 15 41 56" src="https://user-images.githubusercontent.com/14206503/27795487-a39da5c4-6006-11e7-8656-29417238e890.png">

Or you can just use the prebuilt [binary](https://github.com/kmikiy/SpotMenu/releases/download/v1.4.2/SpotMenu.zip)

**Comment by jazzerjazzer** [comment]
@kmikiy thank you so much!

**Comment by kmikiy** [comment]
you're welcome 😉 glad I could help
