### ISSUE TITLE
AMAZING!!!! (and a little request :) - Today Extension

### ISSUE THREAD

**Issue by fabi94music** [kmikiy/SpotMenu#29]
Thank you so much for this awesome app! It is amazing! 
Would be awesome if it could handle multiple players, e.g. iTunes or Apple Music as well.
There is a App called MiniPlay (a widget for Spotify and iTunes for the Notification Center) which is unfortunately not in active development. 
Maybe you could make a great widget for Notification Center Player? 
This one is already awesome!
But it was rather hard to find it. 
PS: The preference tab seems to work not correctly. When I click on it nothing happens.

**Comment by fabi94music** [comment]
Sorry the preferences work just fine! I only was to dumb to put the app into my applications folder :P 
Do you consider to become a registered developer?

**Comment by kmikiy** [comment]
Hey, i'm glad you like the app 🙂

I've been thinking about adding the same interface to the notification center as a today extension. It would definitely require some work, but it's not impossible.

Personally, I rarely use itunes. Although, I could integrate itunes functionality as well but thats currently not a priority for me.

I haven't really considered joining the apple developer program due to the 99 dollar annual fee. iOS/macOS development is just a hobby for me right now.

The preference menu is a bit tricky since the app isn't in foreground most of the time and when you click it, it pops up behind the active app windows almost always

**Comment by fabi94music** [comment]
Hey man, that was quick :) 
Thank you so much for considering that. 
I understand :) 
Just wondering why nobody really writes about your app! It is so simple and amazing! Hope you continue to develop it :)

**Comment by kmikiy** [comment]
How did you find it by the way? 🙂

**Comment by fabi94music** [comment]
over the Spotify community ideas page :)

**Comment by fabi94music** [comment]
https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Now-playing-showing-in-menu-bar/td-p/27571

**Comment by fabi94music** [comment]
Would be also great to have a quick option to change between devices and a volume control :)

**Comment by kmikiy** [comment]
Hey, this is the best I can do for now regarding the notification center issue.

![ezgif com-optimize 1](https://user-images.githubusercontent.com/14206503/28248713-330425b6-6a49-11e7-91e8-f9269deb3a4e.gif)
It was a bumpy road. You can download it [here](https://github.com/kmikiy/SpotMenu/files/1151103/SpotMenu.app.zip)
I'll update the main github readme later on.

The application uses Apple Script to communicate with Spotify, I don't think its possible to access devices through this unfortunately.

Volume control could be possible though, but I don't know where I should put the volume controls to keep it aesthetic

**Comment by fabi94music** [comment]
OMG, you rock!! 
this is much better than MiniPlay or Silicio. I like it very much!! 
Will you add this on version 1.4.3? 
Is it possible to add a update routine for the app to automatically searches for and installs updates?
![screen](https://user-images.githubusercontent.com/29753374/28248870-2c0f00d4-6a4c-11e7-9ed5-dc8f7d02248c.jpg)

**Comment by kmikiy** [comment]
You're welcome :) I'm glad you like it.
I'll see what I can do about automatically updating the app later this week/month.

**Comment by fabi94music** [comment]
Thank you very much!

**Comment by fabi94music** [comment]
Maybe one minor thing (this is complaining on such a high level though :P):
Widget: When no music is played (Spotify app no open) maybe you could show up something like "Open Spotify" instead the silhouette cover.

**Comment by kmikiy** [comment]
Hey @fabi94music could you please create separate issues for each request, so I can keep the issues organised. I will close this issue now as the original request has been addressed.
You can download the latest release [here (version 1.5)](https://github.com/kmikiy/SpotMenu/releases/download/v1.5/SpotMenu.zip)
Feel free to reopen the issue if there is something related.
