### ISSUE TITLE
Keyboard Shortcut To Toggle Showing

### ISSUE THREAD

**Issue by brandonkboswell** [kmikiy/SpotMenu#34]
I would like to be able to see what/who the song/artist is, but I can't have it on my Menubar, and would prefer to not have to grab the mouse to see it. A simple keyboard shortcut to toggle the menu could likely solve this.

**Comment by ssent1** [comment]
I agree, a keyboard shortcut to toggle SpotMenu would be useful.

**Comment by kmikiy** [comment]
Hey, you can download the latest version 
[here](https://github.com/kmikiy/SpotMenu/releases/download/v1.5/SpotMenu.zip)

I now include a toast notification if you press the following key combination:
 <kbd>control</kbd> + <kbd>command</kbd> + <kbd>m</kbd>

![toast](https://user-images.githubusercontent.com/14206503/28485480-3520dda0-6e7a-11e7-85b0-aaf0fb371adf.gif)

I hope this is a good enough solution for you guys. If you have any suggestions let me know.
Feel free to reopen this issue.

**Comment by dennishelbig** [comment]
Hi, great app and great feature!
Would be great if I could define the shortcut to open the notification in the preferences.

It may sound like crying on a high level, but with the shortcut as it is (ctrl+cmd+m), I need to use both hands, would be nice to just need my left hand for it.
