### ISSUE TITLE
SPOTMENUTODAY (title a little bit bulky :P ) (cosmetic issue)

### ISSUE THREAD

**Issue by fabi94music** [kmikiy/SpotMenu#37]
Oh and maybe you could change the title of the widget into something like "Playing now on Spotify".
Now it is absolutely perfect :) Hahah :)

**Comment by kmikiy** [comment]
Yeah the title could be something else. Although the capitalisation is done by macOS so I can't really do anything with that. PLAYING NOW ON SPOTIFY might be too long. Maybe just SPOTMENU?

**Comment by fabi94music** [comment]
Yeah great! or "NOW ON SPOTIFY" but maybe this is too long as well?

**Comment by kmikiy** [comment]
"NOW ON SPOTIFY" is ok I think. It's not longer than for example "FIND MY FRIENDS"

**Comment by kmikiy** [comment]
Fixed it to "NOW ON SPOTIFY". I will make it available in release 1.5.1.

**Comment by fabi94music** [comment]
If you consider to add iTunes as well, maybe something like "Now playing" would be better.
