### ISSUE TITLE
bug: version number of v 1.5 is still at 1.4.2

### ISSUE THREAD

**Issue by fabi94music** [kmikiy/SpotMenu#39]

**Comment by kmikiy** [comment]
hey, where do you see the version number?

**Comment by fabi94music** [comment]
In finder infos

**Comment by kmikiy** [comment]
ohh thanks. fixed it, you can download it [here](https://github.com/kmikiy/SpotMenu/releases/download/v1.5/SpotMenu.zip)

https://github.com/kmikiy/SpotMenu has been updated also

**Comment by fabi94music** [comment]
your welcome :) I really like the app and although it seems I post quite a few issues they are just for perfection :) Really like your quick and kind response
