### ISSUE TITLE
bug: Notification Center and widget crashes

### ISSUE THREAD

**Issue by fabi94music** [kmikiy/SpotMenu#43]
updates to macOS 10.12.6 recently and found that when activating the Notification Center, it freezes. Activity monitor says both the "NOW ON SPOTIFY" widget and Notification Center do not react. I can only force quit both processes. 
Using the built with the new Widget name. 
Strange that only happen a few times. Now it is working...

**Comment by kmikiy** [comment]
I'm closing this issue. Please reopen it if it still occurs!
