### ISSUE TITLE
No Spotify - Open it

### ISSUE THREAD

**Issue by Triloworld** [kmikiy/SpotMenu#6]
If Spotify isn't running then run it after click. It will be usefull because after Spotify is closed it take only places and don't do anything. That would be easy and usefull feature for icon in menu. Thanks ! It work better than other solution. 

If ForceTouch can be used then it can play/pause song. It is usefull?

One more think. Tags in git are better than zip file in repository. After all everybody looking for executable file in that place rather than in source code. :)

**Comment by kmikiy** [comment]
Thanks for the suggestions!

Applications can be started 2 ways, it can be launched **_hidden_** or activated and pops up as the **_frontmost_** application. Which would would suit you best? If you clicked the icon in the menubar and it opened Spotify showing Spotify's main window, or should I only start it, but Spotify's UI wouldn't pop up?

What exactly would you want to be force touched to play/pause music? The menubar icon? 

I'll try to add tags later on today, thanks for the recommendation.

**Comment by Triloworld** [comment]
I think best for all will be launched _hidden_. Just start Spotify and after that we don't have this empty form: 
![zrzut ekranu 2017-01-24 o 15 52 02](https://cloud.githubusercontent.com/assets/2671726/22252048/3303db9e-e24d-11e6-8668-28958bbe94a1.png)

This form won't show and Spotify can be useful without full UI. I don't know if there can be catch force touch but can be use to play/pause song. Small change but combine with open Spotify app hidden can be great shortcut: two click and music play. Often mouse is on top and Spotify don't run in background.

**Comment by kmikiy** [comment]
Now if you click the icon, then Spotify opens up in the background and you can press the play button to start music.
Maybe I could also add button in the popover to open Spotify's UI. What do you think about that?

**Comment by Triloworld** [comment]
I just cannot open spotify by clicking icon (don't working sadly). There is also some strange lag between click and open popover. I think it is nice feature. If 'X' will go to menu on right click then there will be more space for that feature. I don't wan't to close this app accidentally if I miss click. What you think ? and where it be?

**Comment by kmikiy** [comment]
Do you notice a lag every time you click it, or just the first time, what OS X version are you using and how old is your computer?
What should happen is that, if Spotify is not running, SpotMenu will try to launch it, and after it has been launched, the popover will become visible. If Spotify is already running, then the popover show become visible relatively quickly.
