### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by rebdeg** [kmikiy/SpotMenu#60]
I added Dutch translation to the excel file circulating over here. 

Regards,
Reinier de Groot
[Dutch.translation.xlsx](https://github.com/kmikiy/SpotMenu/files/1290870/Dutch.translation.xlsx)

**Comment by kmikiy** [comment]
Wow thanks! I really appreciate it!
I will definitely add it in the next update.
Regards,
Miklós
