### ISSUE TITLE
App crashes when I click on preferences

### ISSUE THREAD

**Issue by patrickbclee** [kmikiy/SpotMenu#63]
Hello! For some reason, the app crashes when I try to click on preferences. Please fix!! Thanks for this great app! Oh I'm running MacOS.

**Comment by kmikiy** [comment]
Hey! which version of SpotMenu and which version of macOS are you running? 

 → About This Mac

Applications Folder → highlight SpotMenu.app → Press space

**Comment by patrickbclee** [comment]
I'm running Sierra version 10.12.3, SpotMenu is version 1.6.0. Thank you!

**Comment by patrickbclee** [comment]
Oh it works now! Sorry but thank you!
