### ISSUE TITLE
can't open preferences 

### ISSUE THREAD

**Issue by vanessaou** [kmikiy/SpotMenu#64]
wanted to see the title of song on the menu bar but when i right click spotmenu and click preference, it quits the program altogether

**Comment by kmikiy** [comment]
Hi!
Could you please try this [pre-release](https://github.com/kmikiy/SpotMenu/files/1348288/SpotMenu.zip) and see if it works? You'll have to delete your previous version manually and replace it.
I think your issue is similar to #63 
Are you also running 1.6.0 and Sierra version 10.12.3?

**Comment by vanessaou** [comment]
i tried deleting and replacing it and it is still not opening preferences up.
I am sierra 10.12.16

**Comment by kmikiy** [comment]
hmm, could you also try an older version? e.g [v1.5](https://github.com/kmikiy/SpotMenu/releases/tag/v1.5) already has all the core features. If this works it could help me with debugging the issue.

**Comment by vanessaou** [comment]
still not working unfortunately

**Comment by kmikiy** [comment]
Here's a new [build](https://github.com/kmikiy/SpotMenu/files/1350362/SpotMenu.zip) with showing song title and artists enabled by default, unfortunately I still haven't found out why it crashes for you.
What language are you using SpotMenu in?
