### ISSUE TITLE
Translation to Català (Catalan) attached

### ISSUE THREAD

**Issue by bcubic** [kmikiy/SpotMenu#69]
Hi!

I translated SpotMenu into Catalan.
See attached file.

[ca.lproj.zip](https://github.com/kmikiy/SpotMenu/files/1404343/ca.lproj.zip)

;)

**Comment by kmikiy** [comment]
thanks! i'll add it to version 1.7
I'll list you as a contributor if its ok with you (https://github.com/kmikiy/SpotMenu#contributors)

**Comment by bcubic** [comment]
Thanks!

**Comment by kmikiy** [comment]
updated readme and published 1.7
it will be available in a couple of minutes
