### ISSUE TITLE
Feature: Right click show menu

### ISSUE THREAD

**Issue by Triloworld** [kmikiy/SpotMenu#7]
This menu can have: 
- Close app - people search for it there obvious.
- Issues - link to this repository
- Some switches (no need separate setting windows) - For example: run on login, alternative theme version.
- Credits (name and surname of creator)
Then "X" can be eventually remove from popup window.

Idea, screenshoot and tutorial (point: Adding a Menu to the Status Item): https://www.raywenderlich.com/98178/os-x-tutorial-menus-popovers-menu-bar-apps.

**Comment by kmikiy** [comment]
Great ideas, i'll start implementing these features and issue #6 on thursday 🙂

**Comment by Triloworld** [comment]
No problem. I just done some work and i will have pull request for this so you can check how it looks and work.

**Comment by Triloworld** [comment]
Added pull request . Check menu entries and overall work if there is some errors. Menu show only on right click and popup on left.

**Comment by TrevorSayre** [comment]
Would like a way to toggle displaying "Artist - Title" in menu bar versus displaying "Artist - Title \n Album" in drop down, I think the right-click menu would be a good place for this toggle

**Comment by kmikiy** [comment]
Added preferences in [Version 1.4](https://github.com/kmikiy/SpotMenu/releases/tag/v1.4). Please check it out and notify me of any issues 🙂
Feel free to reopen issue if anything else is needed

**Comment by kmikiy** [comment]
>Would like a way to toggle displaying "Artist - Title" in menu bar versus displaying "Artist - Title \n Album" in drop down, I think the right-click menu would be a good place for this toggle

@TrevorSayre Please create a separate issue for this 🙂
