### ISSUE TITLE
Do not show title/artist when paused

### ISSUE THREAD

**Issue by mrleblanc101** [kmikiy/SpotMenu#73]
Hi,
First, good job on fixing the click responsiveness of the app.
Second, it would be nice to not show title/artist when paused as it take a lot of status bar space and my Spotify/iTunes is always open enven when I'm not listening to music. You could make this a preference if you think some user don't want this behavior.

**Comment by kmikiy** [comment]
hi, i am considering implementing this!

**Comment by kmikiy** [comment]
Implemented it.
It will be available in release 1.8.
Meanwhile if you want early access you can build the source code or download it [here](https://github.com/kmikiy/SpotMenu/files/1443140/SpotMenu.app.zip)
