### ISSUE TITLE
It is possible to uncheck all display options

### ISSUE THREAD

**Issue by thk686** [kmikiy/SpotMenu#89]
And you never see the application again. I can run it and kill it but I cannot get back to the options menu. Tried uninstalling and reinstalling.

**Comment by kmikiy** [comment]
ill issue a fix tomorrow!

**Comment by kmikiy** [comment]
By Default SpotMenu should always be shown on the menubar when it's running. If no info should be shown, the default icon is visible.

Run the following command in terminal to make the SpotMenu icon setting checked
```sh
defaults write com.KMikiy.SpotMenu showSpotMenuIcon true
```
Then just to be sure start a song or skip to the next song on Spotify
