### ISSUE TITLE
Too much icons on menu bar

### ISSUE THREAD

**Issue by maurojuniorr** [kmikiy/SpotMenu#9]
Hello, I really liked your app, but can I give you a tip? In the title already says, in the menu bar has more icons, we have the icon of spotify and one that appears when the music is playing. I think only the name of the song would be great.

**Comment by kmikiy** [comment]
I'll try to add a settings view where these can customized, because everyone has different preferences

**Comment by maurojuniorr** [comment]
Yes!, your idea is even better!, customization is great! we love it

**Comment by jknlsn** [comment]
Just discovered this app and it's great, agree with the preference option though! First thing I looked for when I installed

**Comment by kmikiy** [comment]
Added preferences in [Version 1.4](https://github.com/kmikiy/SpotMenu/releases/tag/v1.4). Please check it out and notify me of any issues 🙂

**Comment by maurojuniorr** [comment]
Very good! I really liked the customization options, I'm already using it and if I find something wrong I notice

**Comment by jknlsn** [comment]
That's great, thanks!
